### ISSUE TITLE
init script doesnt work at all on debian squeeze

### ISSUE THREAD

**Issue by tobsn** [nicokaiser/node-monit#1]
tried everything, couldnt figure out why... no error, reports started even if app.js doesnt exist.

**Comment by plus-** [comment]
Debian node package is usr/bin/nodejs instead of node. Make sure the script is configured for it.

**Comment by Pegase745** [comment]
I only had to change the first line of the init.d/ script into '#!/bin/bash' and it worked like a charm.

**Comment by chmac** [comment]
@Pegase745 Thanks, that worked for me also.

**Comment by nicokaiser** [comment]
I changed this in 058b546. Thanks for your feedback!
